version: "3.9"
services:
  webapi:
    image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db
    ports:
      - 8080:8080
      - 8081:8081

  postgres:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  db:

volumes:
  postgres:
