version: "3.9"
services:
  webapi:
    image: ${DOCKER_IMAGE}
    deploy:
      labels:
        prometheus-job: webapi
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db
      - infra_metrics
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17.0-alpine
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.volumes==true
      replicas: 1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  db:
  infra_metrics:
    external: true

volumes:
  postgres:
