name: Quality Gate

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'
    
    - name: Run Linter
      run: dotnet format --verify-no-changes
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --collect:"Code Coverage"